version: 1.0.{build}
branches:
  only:
  - develop
image: Ubuntu
init:
- sh: >-
    ls

    cd ~/projects/griddomain-tvtpq

    ls


    sqlcmd -S localhost -U SA -P Password12! -Q 'select @@VERSION'



    sqlcmd -S localhost -U "sa" -P "Password12!" -Q "Use [master]; CREATE DATABASE [AutoTestRead];"



    sqlcmd -S localhost -U "sa" -P "Password12!" -i "GridDomain.Node.Persistence.Sql\Persistence.sql"


    sqlcmd -S localhost -U "sa" -P "Password12!" -i "GridDomain.Node.Persistence.Sql\Human_schema.sql"


    sqlcmd -S localhost -U "sa" -P "Password12!" -i "GridDomain.Scheduling\CreateDatabase.sql"
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}-alfa'
  package_version: '{version}-alfa'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}-alfa'
environment:
  APPVEYOR_SSH_KEY: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBI7S8beSMm0ePKq3CM3r4a0W/7OU+cwb8ZPyMoeeTtz0q0sPHoO1psD1jPh/2+v8UKToLdDJxhtxbkNTv8WeVME=
  APPVEYOR_SSH_BLOCK: true
services: mssql
build_script:
- sh: "set -e \n\nprintenv APPVEYOR_BUILD_VERSION\nprintenv APPVEYOR_BUILD_NUMBER\n\ndotnet build GridDomain.sln -c Release -v Minimal /l:\"/opt/appveyor/build-agent/AppVeyor.MSBuildLogger.dll\"\n\ndotnet pack GridDomain.sln -c Release -v Minimal --include-symbols --include-source --no-build /l:\"/opt/appveyor/build-agent/AppVeyor.MSBuildLogger.dll\""
test_script:
- sh: "ls\n\nrunTests()\n{\n\ntestsName=$1\ntestsFolder=$2\n\ncd $testsFolder\n\ndotnet test --no-build --configuration Release --no-restore --logger trx > TestsOutput.txt\n\nTestResult=$?\npath=~/projects/griddomain-tvtpq/\"$testsFolder\"/bin/Release/netcoreapp2.0/Logs/*\n\necho $path\n\n7z a $testsName\"Output\" TestResults/*\n7z a $testsName\"Logs\" $path\n\nif [ $TestResult -ne 0 ];then\n   echo should exiting...\n   #exit #$TestResult\nfi\n\necho continue \n\ncd ..\n}\n\nrunTests UnitTests GridDomain.Tests.Unit\nrunTests ClusterUnitTests GridDomain.Tests.Unit.Cluster"
artifacts:
- path: '**\GridDomain.*.nupkg'
  name: Packages
- path: '**\*.7z'
  name: UnitTestResults