version: 2.2.{build}
branches:
  only:
  - develop
image: ubuntu
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-alfa'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}-alfa'
  package_version: '{version}-alfa'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}-alfa'
environment:
  WriteModel: Server=(local)\SQL2017;Database=master;User ID=sa;Password=Password12!
  ReadModel: Server=(local)\SQL2017;Database=AutoTestRead;User ID=sa;Password=Password12!
  APPVEYOR_RDP_PASSWORD:
    secure: wdSMAMdS/O0zMUdCuf87Rw==
  Quartz: Server=(local)\SQL2017;Database=Quartz;User ID=sa;Password=Password12!
services: mssql2017
cache: packages  -> **\packages.config
build_script:
- sh: |
    dotnet build GridDomain.sln -c Release -v Minimal
    dotnet pack GridDomain.sln -c Release -v Minimal --include-symbols --include-source --no-build
test_script:
- sh: |
    cd C:\projects\griddomain\GridDomain.Tests.Unit
    dotnet xunit -noshadow -configuration Release -internaldiagnostics -nobuild
artifacts:
- path: '**\GridDomain.*.nupkg'
  name: Packages
deploy:
- provider: NuGet
  server: https://www.myget.org/F/griddomain/api/v2/package
  api_key:
    secure: jF3VOqctqN9MK8lLs+Vlfs2Trv4Gs9BLV/R4HX6ZtC1JQaoezDssjjtP/28Ptkd7
  skip_symbols: false
  symbol_server: https://www.myget.org/F/griddomain/symbols/api/v2/package