// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace GridDomain.Balance.ReadModel.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TableRename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableRename));
        
        string IMigrationMetadata.Id
        {
            get { return "201601212002228_TableRename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
