// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace BusinessNews.ReadModel.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TimeForTransactionHistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TimeForTransactionHistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201606010657264_TimeForTransactionHistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
