 DELETE FROM [MembershipScheduler].[dbo].[QRTZ_TRIGGERS]
 DELETE FROM [MembershipScheduler].[dbo].QRTZ_BLOB_TRIGGERS
 DELETE FROM [MembershipScheduler].[dbo].QRTZ_CALENDARS
 DELETE FROM [MembershipScheduler].[dbo].QRTZ_CRON_TRIGGERS
 DELETE FROM [MembershipScheduler].[dbo].QRTZ_FIRED_TRIGGERS
 DELETE FROM [MembershipScheduler].[dbo].QRTZ_JOB_DETAILS
 DELETE FROM [MembershipScheduler].[dbo].QRTZ_LOCKS
 DELETE FROM [MembershipScheduler].[dbo].QRTZ_PAUSED_TRIGGER_GRPS
 DELETE FROM [MembershipScheduler].[dbo].QRTZ_SCHEDULER_STATE
 DELETE FROM [MembershipScheduler].[dbo].QRTZ_SIMPLE_TRIGGERS
 DELETE FROM [MembershipScheduler].[dbo].QRTZ_SIMPROP_TRIGGERS
 DELETE FROM [MembershipScheduler].[dbo].QRTZ_TRIGGERS