using System;
using GridDomain.Common;
using GridDomain.CQRS;
using GridDomain.CQRS.Messaging;
using GridDomain.EventSourcing;

namespace GridDomain.Node.Configuration.Composition {
    class MessageHandlerFactory<TMessage, THandler> where THandler : IHandler<TMessage>
                                                    where TMessage : class, IHaveSagaId, IHaveId
    {
        private readonly Func<IMessageProcessContext, THandler> _creator;

        protected MessageHandlerFactory(Func<IMessageProcessContext, THandler> creator)
        {
            _creator = creator;
        }

        public THandler Create(IMessageProcessContext context)
        {
            return _creator(context);
        }

        public IMessageRouteMap CreateRouteMap()
        {
            return MessageRouteMap.New<TMessage, THandler>($"autogenerated map for {typeof(TMessage).Name} to {typeof(THandler).Name}");
        }
    }
}