
GO
ALTER TABLE Journal DROP CONSTRAINT PK_Journal;
GO
ALTER TABLE Journal ADD Ordering BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL;
GO
ALTER TABLE Journal ADD CONSTRAINT QU_Journal UNIQUE (PersistenceID, SequenceNr);
GO